"""evidence passage ordinal

Revision ID: 280bf824e990
Revises: 942654681846
Create Date: 2026-10-07 09:36:05.419344

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "280bf824e990"
down_revision: str | Sequence[str] | None = "942654681846"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evidence_passages", sa.Column("ordinal", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evidence_passages", "ordinal")
    # ### end Alembic commands ###
