"""reference citation_key_locked

Revision ID: 97751b314be8
Revises: cabf7898e4e5
Create Date: 2026-10-07 15:55:44.282252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97751b314be8"
down_revision: str | Sequence[str] | None = "cabf7898e4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "references",
        sa.Column("citation_key_locked", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("references", "citation_key_locked")
    # ### end Alembic commands ###
